export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';

export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const CHANGE_TAB = 'CHANGE_TAB';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';

export const LOCATION_PREVIEW_CLICKED = 'LOCATION_PREVIEW_CLICKED';
export const LOCATION_LIST_PAGE_LOADED = 'LOCATION_LIST_PAGE_LOADED';
export const LOCATION_LIST_PAGE_UNLOADED = 'LOCATION_LIST_PAGE_UNLOADED';
export const LOCATION_EDITOR_PAGE_LOADED = 'LOCATION_EDITOR_PAGE_LOADED';
export const LOCATION_EDITOR_PAGE_UNLOADED = 'LOCATION_EDITOR_PAGE_UNLOADED';
export const LOCATION_SUBMITTED = 'LOCATION_SUBMITTED';
export const UPDATE_FIELD_LOCATION_EDITOR = 'UPDATE_FIELD_LOCATION_EDITOR';

export const FLIGHT_PLAN_PAGE_LOADED = 'FLIGHT_PLAN_PAGE_LOADED';
export const FLIGHT_PLAN_PAGE_UNLOADED = 'FLIGHT_PLAN_PAGE_UNLOADED';
export const FLIGHT_PLAN_PAGE_ADD_FLIGHT_STEP = 'FLIGHT_PLAN_PAGE_ADD_FLIGHT_STEP';
export const FLIGHT_PLAN_PAGE_REMOVE_FLIGHT_STEP = 'FLIGHT_PLAN_PAGE_REMOVE_FLIGHT_STEP';
export const UPDATE_FIELD_FLIGHT_PLAN = 'UPDATE_FIELD_FLIGHT_PLAN';

export const PLANE_EDITOR_PAGE_LOADED = 'PLANE_EDITOR_PAGE_LOADED';
export const PLANE_EDITOR_PAGE_UNLOADED = 'PLANE_EDITOR_PAGE_UNLOADED';
export const PLANE_SUBMITTED = 'PLANE_SUBMITTED';
export const UPDATE_FIELD_PLANE_EDITOR = 'UPDATE_FIELD_PLANE_EDITOR';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
